### ISSUE TITLE
This OpenCV build doesn't support current CPU/HW configuration *

### ISSUE THREAD

**Issue by kpssachin** [jitendra29mishra/OpencvInstallation#1]
i installed the opencv and tried to run this code, but it is showing me this error

******************************************************************
* FATAL ERROR:                                                   *
* This OpenCV build doesn't support current CPU/HW configuration *
*                                                                *
* Use OPENCV_DUMP_CONFIG=1 environment variable for details      *
******************************************************************

Required baseline features:
SSE - OK
SSE2 - OK
SSE3 - OK
SSSE3 - OK
SSE4.1 - OK
POPCNT - OK
SSE4.2 - OK
AVX - NOT AVAILABLE
OpenCV Error: Assertion failed (Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup.) in initialize, file /home/sachin/Desktop/opencv/modules/core/src/system.cpp, line 492
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/sachin/Desktop/opencv/modules/core/src/system.cpp:492: error: (-215) Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup. in function initialize

Aborted (core dumped)

[Uploading face_recognizer.zip…]()

**Comment by jmishra01** [comment]
I update opencvInstallation shell file. please check it
